### ISSUE TITLE
Spec Image / Binary storage

### ISSUE THREAD

**Issue by sebastienbeau** [akretion/ak-odoo-incubator#33]
# Objectif

- stocker des pdf et des images sur un acces public (ftp, sftp, s3...)
- gérer le resize des images et l'optimisation de celle-ci
- faire que l'ERP récupère les images ou pdf depuis les url public
- à terme gérer du multilangue (dupliquer les images pour les stocker sous des
  nom d'url différente)

# Implémentation

Utiliser la lib python pour fs==0.5.4

## Module StorageBackend

Module très abstrait qui permet juste de stocker la conf (via keychain) d'un FileStorage et qui implemente les méthodes pour communiquer avec le filestorage

### class StorageBackend

```
   _inherit = 'backend.keychain'
   
   fields:
     - backend_type : (filestore, amazon S3, ...)
     - public_base_url : (url de base pour les cas ou les fichiers sont accessible publiquement)

   method pour intéragir avec le system de fichier


```

### class StorageFile

```
  def _get_filename():
     return "le nom du fichier par rapport à sa source"

  def _compute_file():

  def _inverse_file():
     # stock le fichier sur amazon S3 / sftp / ftp..

  fields:
     - filename : nom du fichier (doit être unique) (champs non traduisible)
     - url : url publique de l'élément, champs calculé (concatène le chemin +
       le nom de l'image)
     - storage_id : lien vers la configuration de l'espace de stockage
     - meta : champs char/jsonb pour par exemple mettre la valeur du resize des images, la lang
     - file_type : fields.Selection (binary/ image)
     - file : fields.Binary(compute=..., inverse=...) permet de saisir l'image et de récupérer l'image a afficher
```

### class AbstractImage

```
  fields:
    - storage_public_ids : o2m storage.public
    - filename : champs doit forcément contenir l'extension (sans
      espace, on le reformat automatiquement via un onchange + warning)
      a terme (V2) réfléchir pour avoir plusieurs champs "fr_filename", "en_filename"...
    - image_full : fields.Image(compute=..., inverse=...) permet de saisir l'image et de récupérer l'image a afficher
    - url_medium : fields.Url(compute=, size=)

    @api.model
    def _get_storage(self)
        return NotImplemented

    def _compute_image(self):
        for field in self._fields:
            if isinstance(field, fields.Url) and hasattr(field, 'size'):
                image_fields.append((field_name, field.size))
        for record in self:
            for field, size in image_fields:
                record[field] = record.resize(size).url

    def resize(self, size):
        self.ensure_one()
        return search_or_create_public_file()

            
```

### Widget

- il faut reprendre le widget des binaire et des images pour qu'il récupère la bonne url

### class ProductImage

```
  _inherit = 'abstract.image'

  def _get_storage():
     xml_id = '....'
     return self.env.ref(xml_id)

  fields:
    - product_tmpl_id
    - product_id
```

### class product_template

```
   fields.Image(compute pour récupérer l'url de l'image principale a la bonne taille)
```

## Reprendre l'interface kanban de Pedro

**Comment by rvalyi** [comment]
Salut, je sais pas trop quelles sont les contraintes, mais pour Zupy, j'arrive a interfacer Odoo avec 
https://github.com/carrierwaveuploader/carrierwave et https://github.com/markevans/dragonfly (via ooor)
peut etre plutot chercher l'integration que de re-inventer la roue. Mais si au pire tu pars pour re-coder, y'a sans doute des bonnes idees a reprendre dans ces 2 projets tres matures.

**Comment by sebastienbeau** [comment]
En faite si on veut avoir un truc méga clean (mais va falloir faire des heures de code !). Il faut que l'on fasse un truc niquel coté python, car dans un cas pur odoo on doit pouvoir récupérer les images du backoffice (small, medium ...) depuis un CDN sans devoir faire des connexion via un serveur rails.
Mais c'est sur que ça a un cout de faire ça. Mais c'est la bonne solution

**Comment by sebastienbeau** [comment]
Work have been started here : https://github.com/akretion/storage
and here : https://github.com/akretion/product-attribute/tree/8.0-image
