### ISSUE TITLE
promotion rule - README misunderstood

### ISSUE THREAD

**Issue by bealdav** [akretion/ak-odoo-incubator#63]
The is branch is available on apps.odoo.com.

Then please before merge in this branch ensure README is correct

- module name
- description 
- author : it's not OCA
- useless parts : configuration, installation, etc.

https://github.com/akretion/ak-odoo-incubator/tree/8.0/sale_promotion_rule
https://github.com/akretion/ak-odoo-incubator/tree/8.0/sale_delivery_promotion_rule

Please use a minimal README model as here
https://github.com/akretion/ak-odoo-incubator/tree/8.0/sale_price_origin

Don't copy/paste a broken template.

If you don't do the right thing at merge event, it'll never done !

**It's really really important. Thanks**

**Comment by sebastienbeau** [comment]
I will fix it today

**Comment by sebastienbeau** [comment]
I should have said next week today ;)

**Comment by bealdav** [comment]
Merci. Tres claire. Parfait
