### ISSUE TITLE
Broken inherit in  stock_default_warehouse_by_company

### ISSUE THREAD

**Issue by bealdav** [akretion/ak-odoo-incubator#71]
@chafique-delli il semble que c'est pas bon là

https://github.com/akretion/ak-odoo-incubator/blob/86e155cee0f32eadd112278e3bb3759e986d4c92/stock_default_warehouse_by_company/models/sale_stock.py#L15

SI un autre module herite de _get_default_warehouse() alors son comportement est ignoré.

@sebastienbeau peux tu confirmer ?

**Comment by chafique-delli** [comment]
@bealdav , fixed by PR: https://github.com/akretion/ak-odoo-incubator/pull/72

**Comment by chafique-delli** [comment]
@bealdav , ping
