### ISSUE TITLE
product_categ_available_pos import bug

### ISSUE THREAD

**Issue by bealdav** [akretion/ak-odoo-incubator#85]
@hparfr 

https://github.com/akretion/ak-odoo-incubator/tree/10-product_categ_available_pos

Sans le module cela passe, avec non

![categ](https://user-images.githubusercontent.com/1853434/37416117-4456b7a8-27ad-11e8-98b0-aa01a541d29d.png)

Merci de checker stp

PS: après ddmrp, bien sur

**Comment by bealdav** [comment]
@hparfr to close ?

**Comment by hparfr** [comment]
Resolved by https://github.com/odoo/odoo/pull/23749
